# Better Alternative to application.properties; Indentation must be fixed

server:
  port: '8082'

spring:
  profiles:
    active: dev

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcapp-dev
    password: djangofrango
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  config:
    activate:
      on-profile: dev
welcome:
  message: Welcome to My World!

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcapp-qa
    password: djangofrango
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  config:
    activate:
      on-profile: qa
welcome:
  message: Welcome to My World!

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcapp-prod
    password: djangofrango
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  config:
    activate:
      on-profile: prod
welcome:
  message: Welcome to My World!

---

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"


